### PR TITLE
Example pricing 

### PR DESCRIPTION
**Pull request by pibizza**
Extending previous example, in particular:

- refactored tests so that they were easier to extend
- added a test for service pricing.

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
Thank you!
Nothing preventing the merge even now, but kindly consider the comments below; also, can you check you commit spaces instead of tabs, so to make it whole consistent in indenting?

**Comment by pibizza** [comment]
@tarilabs I think I fixed them all, including tabs.

**Comment by tarilabs** [comment]
@pibizza thanks! Shall I merge this? Let me know

**Comment by pibizza** [comment]
@tarilabs yes please :+1:

**Pull request merged**
